<?php

namespace CodePress\CodeCategory\Tests\Models;

use CodePress\CodeCategory\Models\Category;
use CodePress\CodeCategory\Tests\AbstractTestCase;

class CategoryTest extends AbstractTestCase
{
    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->migrate();
    }

    public function test_check_if_a_category_can_be_persisted()
    {
        $category = Category::create(array(
            'name' => 'Category Test',
            'active' => true
        ));
        $this->assertEquals('Category Test', $category->name);

        $category = Category::all()->first();
        $this->assertEquals('Category Test', $category->name);
    }

    public function test_check_if_can_assign_a_parent_to_a_category()
    {
        $parentCategory = Category::create(array(
            'name' => 'Parent Test',
            'active' => true
        ));

        $childCategory = Category::create(array(
            'name' => 'Child Test',
            'active' => true
        ));

        $childCategory->parent()->associate($parentCategory)->save();

        $child = $parentCategory->categories()->first();

        $this->assertEquals('Child Test', $child->name);
        $this->assertEquals('Parent Test', $childCategory->parent->name);
    }
}

